### ISSUE TITLE
Can't set retry vars in Github Actions

### ISSUE THREAD

**Issue by grrywlsn** [pactflow/actions#20]
Our Pact checks are taking some time to complete, so we're following the advice in the docs to retry over time. However it doesn't seem like we can set that in the Github Action (only if we swap to CLI).

This is what we expected would work:

```
    - name: can-i-deploy
      uses: pactflow/actions/can-i-deploy@v1.0.1
      env:
        version: 1.2.3
        to_environment: "dev"
        application_name: app
        retry_while_unknown: 5
        retry_interval: 5
```

Is this something that should be added here or is there a better way to handle this?
