### ISSUE TITLE
Inputs are ignored

### ISSUE THREAD

**Issue by DavidJFowler** [pactflow/actions#38]
All the actions specify inputs, e.g. [record-deployment/action.yml](https://github.com/pactflow/actions/blob/main/record-deployment/action.yml):

```yaml
name: "record-deployment"
description: "Record deployment of an application to an environment"
branding:
  icon: "check"
  color: "green"
inputs:
  PACT_BROKER_BASE_URL:
    description: "The url of your pact broker"
    required: true
  PACT_BROKER_TOKEN:
    description: "Your pact broker token"
    required: true
  application_name:
    description: "The name of your application (usually project name)"
    required: true
  version:
    description: "The version of your application (defaults to latest)"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/recordDeployment.sh
      shell: bash
```

However, in the bash scripts, the inputs are ignored and the values of environment variables are used.

**Comment by YOU54F** [comment]
you are correct, they aren't used as you have to map `with` (input) & `env` vars. we currently only support env vars, which can be set either at a top level of a workflow, or at an individual action level if you want different values.

If this is an issue, we would be happy to accept a PR that can deal with both, we would just need to make a decision as to which takes precedence if both are specified (workflow input vs env var), pick one and warn the user.

Or potentially have an option to fail fast, if multiple options are specified so the user has an opt-in chance to rectify

**Comment by twalshOG** [comment]
@YOU54F 
This is extremely unintuitive.
The action says some parameters are required, but they aren't.
Even if you add them, they are 100% ignored.

### Examples of why this is so unintuitive 
**Work, but parser gives me the following error**
_Missing required inputs: `PACT_BROKER_BASE_URL`, `PACT_BROKER_TOKEN`, `application_name`, `to`_
``` yaml
      - uses: pactflow/actions/can-i-deploy@v1.3.0
        env:
          to: development
          version: ${{ env.VERSION }}
          application_name: "NAME"
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
```

**Works, but parameters are ignored** 
``` yaml
      - uses: pactflow/actions/can-i-deploy@v1.3.0
        with:
          PACT_BROKER_BASE_URL: Anything
          PACT_BROKER_TOKEN: Anything 
          application_name: Anything
          version: Anything
          to: Anything
        env:
          to: development
          version: ${{ env.VERSION }}
          application_name: "NAME"
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
```

**Fails, but the parser is happy**
_This should be what actually works!_
``` yaml
      - uses: pactflow/actions/can-i-deploy@v1.3.0
        with:
          to: development
          version: ${{ env.VERSION }}
          application_name: "NAME"
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
```


### Recommendation
Instead of this
``` yaml
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/canideployTo.sh
      shell: bash
```

**Do this:**
_*Works without a version break_
``` yaml
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/canideployTo.sh
      shell: bash
      env:
        PACT_BROKER_TOKEN: ${{ inputs.PACT_BROKER_TOKEN || env.PACT_BROKER_TOKEN }}
        PACT_BROKER_BASE_URL: ${{ inputs.PACT_BROKER_BASE_URL || env.PACT_BROKER_BASE_URL }}
        application_name: ${{ inputs.application_name || env.version }}
        version: ${{ inputs.version || env.OTHER }}
        latest: ${{ inputs.latest || env.latest }}
        to: ${{ inputs.to || env.to }}
        retry_while_unknown: ${{ inputs.retry_while_unknown || env.retry_while_unknown }}
        retry_interval: ${{ inputs.retry_interval || env.retry_interval }}
```
**Or this:**
_*Works but should be a major version (v1 -> v2) break_

``` yaml
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/canideployTo.sh
      shell: bash
      env:
        PACT_BROKER_TOKEN: ${{ inputs.PACT_BROKER_TOKEN }}
        PACT_BROKER_BASE_URL: ${{ inputs.PACT_BROKER_BASE_URL }}
        application_name: ${{ inputs.application_name }}
        version: ${{ inputs.version }}
        latest: ${{ inputs.latest }}
        to: ${{ inputs.to }}
        retry_while_unknown: ${{ inputs.retry_while_unknown }}
        retry_interval: ${{ inputs.retry_interval }}
```
