### ISSUE TITLE
Publishing on GitHub Market Place

### ISSUE THREAD

**Issue by JP-Ellis** [pactflow/actions#72]
## Summary

To publish out `pactflow/actions` repo on the [GitHub Actions Marketplace](https://github.com/marketplace?query=pactflow&type=actions)

## Background

The GitHub Marketplace would significantly increase the discoverability of our action. It would also help give confidence to end users by using an official action as opposed to one of the ones that already exist from third parties.

## Complication

This repo contains a number of actions which have to be accessed by specifying the path:

```yaml
- uses: pactflow/actions/can-i-deploy@v2
  with:
    application_name: my-consumer-app
    broker_url: ${{ secrets.PACT_BROKER_BASE_URL }}
    token: ${{ secrets.PACT_BROKER_TOKEN }}
    version: "1.0.1"
```

Unfortunately, these sub-actions cannot be published to the market place as-is.

To get around this, I would suggest we create a single 'front' that then dispatches the correct sub-action. For example, to call the `can-i-deploy` action above, I envisage the following:

```yaml
- uses: pactflow/actions@v2
  with:
    action: can-i-deploy   # <- this determine which sub-action to invoke
    application_name: my-consumer-app
    broker_url: ${{ secrets.PACT_BROKER_BASE_URL }}
    token: ${{ secrets.PACT_BROKER_TOKEN }}
    version: "1.0.1"
```

The main downside of this is that the parameters for this 'front' will have to consist of the union of all parameters for all sub-actions. This will have a slight negative impact within IDEs as the completions won't be as nice; however, most actions share a number of common parameters so the union of all parameters should not be too bad hopefully.
